In [2]:
import numpy as np
import pandas as pd

In [3]:
s= pd.Series([1, 4, 6, 6, 5, 12, 3], index= ['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7'])

In [4]:
s.r2

np.int64(4)

In [5]:
s[1]

C:\Users\Ala\AppData\Local\Temp\ipykernel_9888\878419959.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]

np.int64(4)

In [7]:
s.values

array([ 1,  4,  6,  6,  5, 12,  3])

In [8]:
s.index

Index(['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7'], dtype='object')

In [9]:
s.value_counts()

6     2
1     1
4     1
5     1
12    1
3     1
Name: count, dtype: int64

In [11]:
df= pd.DataFrame([[1,2], [3,4], [5,6]], index= ['r1', 'r2', 'r3'], columns= ['C1', 'C2'] )
df

    C1  C2
r1   1   2
r2   3   4
r3   5   6

In [15]:
df[1:2]

    C1  C2
r2   3   4

In [16]:
df[:2]

    C1  C2
r1   1   2
r2   3   4

In [17]:
df['C1']

r1    1
r2    3
r3    5
Name: C1, dtype: int64

In [19]:
df.iloc[2, 1]

np.int64(6)

In [20]:
df.values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
df[df > 1]

     C1  C2
r1  NaN   2
r2  3.0   4
r3  5.0   6

In [23]:
df.index

Index(['r1', 'r2', 'r3'], dtype='object')

In [24]:
df.columns

Index(['C1', 'C2'], dtype='object')

In [25]:
df.head()

    C1  C2
r1   1   2
r2   3   4
r3   5   6

In [27]:
df.tail(2)

    C1  C2
r2   3   4
r3   5   6

In [29]:
df.T #Transpose Columns to Rows

    r1  r2  r3
C1   1   3   5
C2   2   4   6

In [32]:
df.drop('r3', axis= 0)

    C1  C2
r1   1   2
r2   3   4

In [31]:
df.drop('C1', axis= 1)

    C2
r1   2
r2   4
r3   6

In [33]:
df.describe()

        C1   C2
count  3.0  3.0
mean   3.0  4.0
std    2.0  2.0
min    1.0  2.0
25%    2.0  3.0
50%    3.0  4.0
75%    4.0  5.0
max    5.0  6.0

In [34]:
df = pd.DataFrame({ 'r1':[1,4], 'r2':[2,5], 'r3':[3,6] })
df

   r1  r2  r3
0   1   2   3
1   4   5   6

In [37]:
data = {'Name': ['Ala', 'Scott', 'Jean'], 'Location': ['Iran', 'Saidasi', 'France'], 'Age': [18, 39, 36]}

In [38]:
df = pd.DataFrame(data)
df

    Name Location  Age
0    Ala     Iran   18
1  Scott  Saidasi   39
2   Jean   France   36

In [39]:
df.sort_index(axis= 1)

   Age Location   Name
0   18     Iran    Ala
1   39  Saidasi  Scott
2   36   France   Jean

In [40]:
df.sort_index(axis= 0, ascending= False)

    Name Location  Age
2   Jean   France   36
1  Scott  Saidasi   39
0    Ala     Iran   18

In [41]:
df.sort_values(by='Age')

    Name Location  Age
0    Ala     Iran   18
2   Jean   France   36
1  Scott  Saidasi   39

In [44]:
df[df.Age < 30]

  Name Location  Age
0  Ala     Iran   18

In [45]:
df.iloc[1][2]

C:\Users\Ala\AppData\Local\Temp\ipykernel_9888\65333983.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][2]

np.int64(39)

In [46]:
df.iloc[1]['Age']

np.int64(39)

In [47]:
pd.DataFrame(np.random.randn(10,4))

          0         1         2         3
0 -1.233987 -1.086882 -0.755280 -0.700564
1  0.719359 -1.288903  0.413106  1.607012
2 -0.420172  0.083402 -1.219533 -0.845508
3  0.960672  0.765663 -2.068265 -0.172732
4 -1.397057  0.975996 -0.570593 -0.490021
5  1.222031  2.405088  0.263319  0.651765
6  0.697550 -0.103834  0.481093 -0.458982
7 -0.235613 -1.826222 -0.972118  0.404194
8  0.578067 -0.299389  0.465752 -0.052295
9  0.427860  0.518536 -0.800313  1.457523